package com.hacks.devbackend.enums;

public enum Category {
	PHYCHOLOGY, SCIENCE, TECHNOLOGY, MAKE_MONEY, GAME, HUMOR, TRENDS, DEEPWEB, HORROR, ANNOUNCEMENTS,
	PRESONALITY_DEVELOPMENT, SERIAL_KILLER, SEXUALITY, OTHER
}
